version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: cat-backend:latest
    ports:
      - "8080:8080"
    environment:
      THECATAPI_KEY: "live_JBT0Ah0Nt12iyl2IpjQVLDWjcLk0GQwf4zI9wBMfmfejKmcC31mOJp4yJz5TsOUP"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 